### ISSUE TITLE
Site is not providing URLs anymore

### ISSUE THREAD

**Issue by Pelorojo** [URLstream/urlstream.link#1] opened 2024-07-25 10:33 UTC
You'll still get search results but all station will have format "@ null Kbit/s" and if you try to copy the url, it will copy "://" only.

**Comment by streamURL** [comment] 2024-07-25 10:45
Thanks for flagging. Not sure what happened (still investigating the log files), but restarting the database fixed the issue for now.

**Comment by Pelorojo** [comment] 2024-07-25 19:40
Not sure if it's really fixed, the majority of the channels just do not work /anymore.

**Comment by streamURL** [comment] 2024-07-25 20:03
An unnatural increase in traffic has been recorded, exceeding the database's memory capacity. It is currently unclear whether the website has gained popularity (unlikely) or if an app is sending automated requests to the website, for which it is not designed. Measurement techniques will be implemented to better understand the traffic. Once more background information is available, either the cause will be addressed or resources will be increased. The issue will remain open until the investigations are complete.

Apologies for any inconvenience caused.

**Comment by streamURL** [comment] 2024-07-30 16:25
An unplanned update was released to prevent the issue from occurring in the future.

Monitoring:
- The threshold for high memory utilization has been lowered to ensure notifications are triggered before utilization reaches critical levels.
- In addition to standard checks for host and service activity, the system now also verifies whether search queries return valid results.

Data Queries:
- The source code has been optimized to reduce the number of database queries, thereby decreasing the database’s memory consumption.

Application Resources:
- Available resources have been increased to improve performance.

New Feature: Rate Limiting
- At the application layer, the system now monitors the volume and type of requests to ensure they remain within normal thresholds. Requests that deviate significantly will lead to a permanent ban. Power users can apply for an exemption via a newly introduced form.


Please reopen this ticket in case you encounter this issue again. Thank you.

**Closed as completed** 2024-07-30 16:26 UTC
Labels: bug
